### PR TITLE
Fix the concurrent modification exception when kafka listener is initialized outside of a main function

### PR DESCRIPTION
**Pull request by dilanSachi**
## Purpose
When the `kafka:Listener` is initialized outside a main function as depicted in the issue, the service `start` function gets called twice, once by the runtime and the second time by the user. This PR will introduce a check to make sure to stop starting the consumer for a second time which will result in a `concurrrentModificationException`.
## Examples
N/A
## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1780

### CODE REVIEW

**Comment by shafreenAnfar** [comment]
In that case, there is nothing to fix right. I think it is because we created the listener as follows,

```ballerina
listener kafka:Listener kafkaListener = new (kafka:DEFAULT_URL, consumerConfigs);
```
But not as follows,
```ballerina
kafka:Listener kafkaListener = new (kafka:DEFAULT_URL, consumerConfigs);
```
> **Note**: There is no `listener` keyword in front

So if do the latter there is no issue right ? I mean runtime does not call `start()` right ?

**Comment by dilanSachi** [comment]
> In that case, there is nothing to fix right. I think it is because we created the listener as follows,
> 
> ```ballerina
> listener kafka:Listener kafkaListener = new (kafka:DEFAULT_URL, consumerConfigs);
> ```
> 
> But not as follows,
> 
> ```ballerina
> kafka:Listener kafkaListener = new (kafka:DEFAULT_URL, consumerConfigs);
> ```
> 
> > **Note**: There is no `listener` keyword in front
> 
> So if we do the latter there is no issue right ? I mean runtime does not call `start()` right ?

Yes. If it is initiated as above, no issue is raised.

**Comment by dilanSachi** [comment]
Closing the PR as the listener can be initialized as `kafka:Listener kafkaListener = new (kafka:DEFAULT_URL, consumerConfigs);` without any issue.

**Comment by aashikam** [comment]
I tried this with `Ballerina SL beta 2` and `Kafka 2.1.0-beta.2.2`. The following services exit right after starting. 

1. Listener created inside main
```ballerina
import ballerina/log;
import ballerinax/kafka;

configurable string TOPIC = "test-error";

public function main() returns error? {
    kafka:ConsumerConfiguration consumerConfigs = {
        groupId: "something",
        topics: [TOPIC],
        pollingInterval: 1,
        autoCommit: false
    };

    kafka:Listener kafkaListener = check new (kafka:DEFAULT_URL, consumerConfigs);

    check kafkaListener.attach(consumerService);
    check kafkaListener.'start();
}

kafka:Service consumerService =
service object {
    remote function onConsumerRecord(kafka:Caller caller,
                                kafka:ConsumerRecord[] records) returns error? {
        // do something with records

        kafka:Error? commitResult = caller->commit();

        if commitResult is error {
            log:printError("Error occurred while committing the offsets for the consumer.", 'error = commitResult);
        }
    }
};

```

2. Listener created outside main 
```ballerina
import ballerina/log;
import ballerinax/kafka;

configurable string TOPIC = "test-error";

kafka:ConsumerConfiguration consumerConfigs = {
    groupId: "something",
    topics: [TOPIC],
    pollingInterval: 1,
    autoCommit: false
};

kafka:Listener kafkaListener = check new (kafka:DEFAULT_URL, consumerConfigs);

public function main() returns error? {
    check kafkaListener.attach(consumerService);
    check kafkaListener.'start();
}

kafka:Service consumerService =
service object {
    remote function onConsumerRecord(kafka:Caller caller,
                                kafka:ConsumerRecord[] records) returns error? {
        // do something with records

        kafka:Error? commitResult = caller->commit();

        if commitResult is error {
            log:printError("Error occurred while committing the offsets for the consumer.", 'error = commitResult);
        }
    }
};
```

Better if this is tested in a separated ballerina project instead of tests. Also, this might be changed in the latest pack.

**Comment by dilanSachi** [comment]
@aashikam tried it out on both beta2 and beta3 rc3. The service exits after getting started. However it does not exit if it is initialized in the module level as 
```ballerina
listener kafka:Listener kafkaListener = new (kafka:DEFAULT_URL, consumerConfigs);
```
with the above change.

**Comment by shafreenAnfar** [comment]
I think falling off the `main` is expected. To void that user must use the below,

https://ballerina.io/learn/by-example/dynamic-listener.html?is_ref_by_example=true

**Pull request closed without merging**
